# List of gitignore style paths to include for quantification.
# If populated, only files matching these patterns are included for counting.
# If empty, everything is included (can be filtered out by the next option "Excluded").
Included: 

# List of gitignore style paths to exclude from quantification.
# "Included" is given preference. If "Included" above is set, "Excluded" is ignored.
Excluded:
- node_modules/

# The operation types to consider. Only "Add" and "Delete" are possible.
# At this point, specifying single option is not supported, both "Add" and "Delete" must be specified.
GitOperationType:
- Add
- Delete

# Specify thresholds for applying labels, along with their configurations.
Thresholds:
  
  # Operation type is required.
- GitOperationType:
  - Add
  - Delete
  
  # Value specifies the number at which this threshold ends for the operation types specified above.
  Value: 10

  # The label that should be used as an output when a pull request falls into this threshold.
  Label: Extra Small

  # Color to use for outputting the above label.
  Color: Green

  # Formula to use to combine the "Add" and "Delete" operations. 
  # Supported values: Sum, Avg, Min, Max
  Formula: Sum

- GitOperationType:
  - Add
  - Delete
  Value: 40
  Label: Small
  Color: Green
  Formula: Sum

# Options that are differ by the code language.
# Only C# is supported right now.
LanguageOptions:

  # Ignore spaces and newlines.
  IgnoreSpaces: true

  # Ignore comments.
  IgnoreComments: true

  # Ignore code block separators. "{", "}", "{}".
  IgnoreCodeBlockSeparator: true

DynamicBehaviour: false

# Ignore files that are only renamed (as detected by git).
IgnoreRenamed: true

# Ignore files that are copied (as detected by git).
IgnoreCopied: true

# auto-generated sections below...

# Percentiles generated by PullRequestQuantifier for labeling changes with a repository context percentile.
AdditionPercentile:
  0: 0
  1: 2
  2: 4
  999: 99.965988159179688
  1000: 99.999320983886719
DeletionPercentile:
  0: 0
  1: 2
  999: 99.965988159179688
  1000: 99.999320983886719
FormulaPercentile:
- Item1: Sum
  Item2:
    0: 0
    1: 2
    999: 99.965988159179688
    1000: 99.999320983886719

