name: "AWS SSM Parameter Store Writer"
description: "Stores a secure string in amazon SSM Agent."
inputs:
  aws-region:
    required: true
    description: "The AWS Region to use"
  ssm-path:
    description: "The Path of the SSM Parameter Store path to store"
    required: true
  ssm-value-description:
    description: "A description of the value being inserted into SSM"
    default: ""
  ssm-value:
    description: "The value to be stored in the SSM Parameter Store Path"
    required: true
  ssm-value-type:
    description: "The value type to store the SSM Parameter (String | StringList | SecureString)"
    required: true
    default: "SecureString"
  ssm-value-overwrite:
    description: "Overwrite the value of the SSM Parameter when inserting"
    default: true
  ssm-kms-key-id:
    description: "The AWS KMS Key ARN to use to encrypt the key"
    default: ""
runs:
  using: "node12"
  main: "index.js"
