name: test_pull_request
on:
  pull_request:
    branches:
      - master
jobs:
  add_to_ssm:
    runs-on: ubuntu-latest
    name: Test in a github runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Add SecureString to SSM
        uses: ./
        with:
          ssm-path: "/dwardu89/hello"
          ssm-value: ${{ secrets.SSM_VALUE_EXAMPLE }}
          aws-region: eu-west-1
      - name: Add String to SSM Step
        uses: ./
        with:
          ssm-path: "/dwardu89/hello"
          ssm-value: ${{ secrets.SSM_VALUE_EXAMPLE }}
          ssm-value-type: "String"
          aws-region: eu-west-1
      - name: Add String to SSM Step
        uses: ./
        with:
          ssm-path: "/dwardu89/hello"
          ssm-value: ${{ secrets.SSM_VALUE_EXAMPLE }}
          ssm-value-type: "String"
          aws-region: eu-west-1

  add_to_ssm_on_container:
    runs-on: Ubuntu-20.04
    name: Test in a node container
    container: node:12.20.1-alpine3.10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Add SecureString to SSM
        uses: ./
        with:
          ssm-path: "/dwardu89/hello"
          ssm-value: ${{ secrets.SSM_VALUE_EXAMPLE }}
          aws-region: eu-west-1
      - name: Add String to SSM Step
        uses: ./
        with:
          ssm-path: "/dwardu89/hello"
          ssm-value: ${{ secrets.SSM_VALUE_EXAMPLE }}
          ssm-value-type: "String"
          aws-region: eu-west-1

  add_to_ssm_on_container_and_environment:
    runs-on: Ubuntu-20.04
    name: Test in a node container and environment
    container: node:12.20.1-alpine3.10
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Add SecureString to SSM
        uses: ./
        with:
          ssm-path: "/dwardu89/hello"
          ssm-value: ${{ secrets.SSM_VALUE_EXAMPLE }}
          aws-region: eu-west-1
      - name: Add String to SSM Step
        uses: ./
        with:
          ssm-path: "/dwardu89/hello"
          ssm-value: ${{ secrets.SSM_VALUE_EXAMPLE }}
          ssm-value-type: "String"
          aws-region: eu-west-1

  check_semver_label:
    name: Check for semantic version label
    runs-on: Ubuntu-20.04
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  check_pull_request_type:
    name: Check for pull request type label
    runs-on: Ubuntu-20.04
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: bug,enhancement,chore
          repo_token: ${{ secrets.GITHUB_TOKEN }}
